### PR TITLE
docs: Move CONTRIBUTING.md to documentation website

### PR DESCRIPTION
**Pull request by devastator99**

### CODE REVIEW

**Comment by baggiponte** [comment]
Ciao @devastator99 and thank you for your contribution! I am afraid I did not fill the issue #195 well enough. I did not expect someone to pick that up so soon, I am really grateful for your help 😊

I would like to preserve the `CONTRIBUTING.md` file but have it point to the documentation page on our docs. A bit like how Polars does it, see [here](https://github.com/pola-rs/polars/blob/main/CONTRIBUTING.md).

I think the steps are as follows:

1. Copy CONTRIBUTING.md under `docs/contributing.md`
2. Update the [our mkdocs](https://github.com/functime-org/functime/blob/ba2348d2bb681f2d33ced280696e1cf97233a09a/mkdocs.yml#L53) to display the contributing guide under the Developer Guide.
3. Update the old contributing.md to point at the docs.

Do you agree with this action plan? Would you like to implement that?

Thanks!

**Comment by devastator99** [comment]
> Ciao @devastator99 and thank you for your contribution! I am afraid I did not fill the issue #195 well enough. I did not expect someone to pick that up so soon, I am really grateful for your help 😊
> 
> I would like to preserve the `CONTRIBUTING.md` file but have it point to the documentation page on our docs. A bit like how Polars does it, see [here](https://github.com/pola-rs/polars/blob/main/CONTRIBUTING.md).
> 
> I think the steps are as follows:
> 
> 1. Copy CONTRIBUTING.md under `docs/contributing.md`
> 2. Update the [our mkdocs](https://github.com/functime-org/functime/blob/ba2348d2bb681f2d33ced280696e1cf97233a09a/mkdocs.yml#L53) to display the contributing guide under the Developer Guide.
> 3. Update the old contributing.md to point at the docs.
> 
> Do you agree with this action plan? Would you like to implement that?
> 
> Thanks!


I'd be happy to handle the issue !

**Comment by baggiponte** [comment]
Ciao, thanks for the prompt reply. Will have a look at this later this weekend. Thanks for the help! 😊

**Comment by baggiponte** [comment]
Superseded by #201

**Pull request closed without merging**
