### PR TITLE
refactor: Properly annotate `train_test_split`

### PR DESCRIPTION
**Pull request by baggiponte**
This has been bugging me for a while. Though I can't get rid of one error:

image

@FBruzzesi have any ideas? (Taking the liberty to tag @marcogorelli too, whom I know hates function overloads)

### CODE REVIEW

**Comment by baggiponte** [comment]
Another idea would be to remove the `eager` argument and make it a `mode: Literal["eager", "lazy"]` - which I would *significantly* prefer. But the boolean `eager` is also widely used in Polars, so I wanted to stay consistent with that (and change even less code).

**Comment by FBruzzesi** [comment]
I think you need to add another overload-ed specification:

```py
@overload
def _splitter_train_test(
    X: Union[pl.DataFrame, pl.LazyFrame],
    test_size: Union[int, float],
    eager: bool,
) -> Union[Tuple[pl.DataFrame, pl.DataFrame], Tuple[pl.LazyFrame, pl.LazyFrame]]: ...
```

With that inplace I am not getting any more complaint

**Comment by MarcoGorelli** [comment]
yup - I'd also suggest
```
eager: Literal[False] = ...,
```
as that's the default

> Taking the liberty to tag @MarcoGorelli too, whom I know hates function overloads

😄 they're ok, just don't overdo them

**Comment by baggiponte** [comment]
> yup - I'd also suggest
> 
> ```
> eager: Literal[False] = ...,
> ```
> 
> as that's the default

Where would you add that?

> I think you need to add another overload-ed specification:

So I need three overload, plus the function body, for one boolean variable argument?

**Comment by MarcoGorelli** [comment]
> Where would you add that?

where you already have `eager: Literal[False]`, just add ` = ...` at the end

**Comment by baggiponte** [comment]
> > Where would you add that?
> 
> where you already have `eager: Literal[False]`, just add ` = ...` at the end

Oh clear. I didn't really understand where I should do that: only for the parameters that have default values that I am overriding?

**Pull request merged**
